---
abstract: 'Property-Based Testing for Perl 5'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Stashable: '2.01'
  Data::Object::Try: '2.02'
  Data::Random: '0.13'
  Test::Auto: '0.10'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Ability
requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Stashable: '2.01'
  Data::Object::Try: '2.02'
  Data::Random: '0.13'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/iamalnewkirk/test-ability/issues
  homepage: https://metacpan.org/pod/Test::Ability
  repository: git://github.com/iamalnewkirk/test-ability.git
version: '0.03'
x_authority: cpan:AWNCORP
x_generated_by_perl: v5.30.1
x_serialization_backend: 'YAML::Tiny version 1.73'
