---
name: Test-Ability
desc: Property-Based Testing for Perl 5
main: lib/Test/Ability.pm
init: 0.01

deps:
- "strict = 0"
- "warnings = 0"
- "routines = 0"
- "Data::Object::Class = 2.02"
- "Data::Object::ClassHas = 2.01"
- "Data::Object::Role::Buildable = 0.03"
- "Data::Object::Role::Stashable = 2.01"
- "Data::Object::Try = 2.02"
- "Data::Random = 0.13"

depstest:
- "strict = 0"
- "warnings = 0"
- "routines = 0"
- "Data::Object::Class = 2.02"
- "Data::Object::ClassHas = 2.01"
- "Data::Object::Role::Buildable = 0.03"
- "Data::Object::Role::Stashable = 2.01"
- "Data::Object::Try = 2.02"
- "Data::Random = 0.13"
- "Test::Auto = 0.10"

make:

- base: .
  edit: 0
  file: dist.ini
  vars: project.yaml
  uses:
  - perl/dzil

- base: .
  edit: 0
  file: lib/Test/Ability.pm
  vars: test-ability.yaml
  uses:
  - perl/class

- base: .
  edit: 0
  file: t/Test_Ability.t
  vars: test-ability.yaml
  uses:
  - perl/test
